"""add_relations_and_indexes

Revision ID: fbeb402f511b
Revises: 53a722588816
Create Date: 2026-05-15 21:45:34.439211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbeb402f511b'
down_revision: Union[str, Sequence[str], None] = '53a722588816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('reading_value', sa.Integer(), nullable=False),
    sa.Column('reading_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meter_readings_bill_id'), 'meter_readings', ['bill_id'], unique=False)
    op.create_index(op.f('ix_meter_readings_id'), 'meter_readings', ['id'], unique=False)
    op.create_index(op.f('ix_meter_readings_reading_date'), 'meter_readings', ['reading_date'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_bill_id'), 'payments', ['bill_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='requeststatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_bill_id'), 'service_requests', ['bill_id'], unique=False)
    op.create_index(op.f('ix_service_requests_created_at'), 'service_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_service_requests_id'), 'service_requests', ['id'], unique=False)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.add_column('bills', sa.Column('service_type', sa.Enum('ELECTRICITY', 'WATER', 'GAS', 'HEATING', name='servicetype'), nullable=False))
    op.add_column('bills', sa.Column('created_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=True))
    op.add_column('bills', sa.Column('updated_at', sa.DateTime(), server_default='CURRENT_TIMESTAMP', nullable=True))
    op.create_index(op.f('ix_bills_address'), 'bills', ['address'], unique=False)
    op.create_index(op.f('ix_bills_service_type'), 'bills', ['service_type'], unique=False)
    op.drop_column('bills', 'accruals')
    op.drop_column('bills', 'readings')
    op.drop_column('bills', 'requests')
    op.drop_column('bills', 'payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('payments', sa.INTEGER(), nullable=False))
    op.add_column('bills', sa.Column('requests', sa.VARCHAR(), nullable=True))
    op.add_column('bills', sa.Column('readings', sa.INTEGER(), nullable=False))
    op.add_column('bills', sa.Column('accruals', sa.INTEGER(), nullable=False))
    op.drop_index(op.f('ix_bills_service_type'), table_name='bills')
    op.drop_index(op.f('ix_bills_address'), table_name='bills')
    op.drop_column('bills', 'updated_at')
    op.drop_column('bills', 'created_at')
    op.drop_column('bills', 'service_type')
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_created_at'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_bill_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_bill_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_meter_readings_reading_date'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_id'), table_name='meter_readings')
    op.drop_index(op.f('ix_meter_readings_bill_id'), table_name='meter_readings')
    op.drop_table('meter_readings')
    # ### end Alembic commands ###
